name: Formato Automático (HTML y CSS)

on:
  push:
    branches:
      - main
      - master
      - feature/Johan-laverde

jobs:
  prettier:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js en el servidor
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ejecutar Prettier de forma nativa
        run: npx prettier --write **/*.{html,css}

      - name: Guardar y subir cambios corregidos
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: formato automático de HTML/CSS [skip ci]"
