name: Formato Automático (HTML y CSS)

on:
  push:
    branches:
      - main
      - master
      - feature/Johan-laverde # Tu rama actual

jobs:
  prettier:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Ejecutar Prettier (Dar formato a HTML y CSS)
        uses: prettier/prettier-action@v0.3.1 # 👈 Cambiado por la acción oficial estable
        with:
          # Busca y formatea todos tus archivos HTML y CSS
          prettier_options: --write **/*.{html,css}
          commit_message: "style: formato automático de HTML/CSS [skip ci]"
